version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github_actions
    commit-message:
      prefix: ci
    groups:
      actions:
        update-types:
          - minor
          - patch
