[workspace]
changelog_update = true
git_tag_enable = false
git_release_enable = false
release_always = false
semver_check = false
release_commits = '^(feat|fix|perf|refactor|docs|build)(\(.+?\))?!?:'
pr_name = "chore: release{% if package is defined and version is defined %} {{ package }} v{{ version }}{% endif %}"
pr_labels = ["release"]
publish_timeout = "10m"

[[package]]
name = "kwokka"
semver_check = true

[changelog]
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^docs", group = "Documentation" },
  { message = "^build", group = "Build" },
  { message = '^(ci|chore|test|revert)(\(.+?\))?!?:', skip = true },
  { message = ".*", group = "Other" },
]
