[workspace]
changelog_update = true
git_tag_enable = false
git_release_enable = false
release_always = false
semver_check = false
pr_labels = ["release"]
publish_timeout = "10m"

[[package]]
name = "kwokka"
semver_check = true

[changelog]
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^docs", group = "Documentation" },
  { message = "^test", group = "Testing" },
  { message = "^build", group = "Build" },
  { message = "^security", group = "Security" },
  { message = "^revert", group = "Reverts" },
  { message = "^(ci|chore)", skip = true },
  { message = ".*", group = "Other" },
]
